# Numpy

In [1]:
import numpy as np

In [2]:
minhaLista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
minhaLista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(minhaLista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(minhaLista)

list

In [6]:
#Primeiro valor = inicio
#Segundo valor = fim
#Terceiro valor = salto
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#Cria uma matriz identidade mxn (deixe apenas um valor para ser usado como a ordem)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#Primeiro valor = inicio
#Segundo valor = fim
#Terceiro valor = quantidade de numeros igualmente "espaçados"
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
#Cria uma lista de numeros aleatórios equiprováveis
#Multiplique por 100 por exemplo, para ter números entre 0 e 100 (padrão entre 0 e 1)
np.random.rand(5,4) * 100

array([[16.07282001, 71.09209916, 51.07637561, 99.29583893],
       [53.1331326 , 80.86854689, 97.77472981, 99.20156479],
       [53.13100936, 55.00350134, 99.70962533, 21.95062296],
       [77.79683951, 53.71172417, 20.78504402, 52.34832679],
       [87.46140113, 33.97841173, 71.04393819, 70.33523721]])

In [13]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
###IMPORTANTE###
# Caso o método copy() não seja usado, o arr2 é tratado como uma referencia a arr, ou seja, alterações feitas 
# em arr2 vão ser aplicadas em arr também
arr2 = arr[:3].copy()
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
#Forma eficiente de tratar arrays em numpy
arr[:4,3:]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39]])

In [16]:
#Forma de filtrar um array (no caso, filtrei o array arrand para mostrar apenas valores maiores que 5)
arrand = np.random.rand(5,10) * 10
bol = arrand > 5
arrand[bol]

array([8.1720853 , 5.76370637, 6.5574627 , 8.29466856, 5.82704941,
       8.0662472 , 6.18467371, 9.0243331 , 6.22116244, 5.38921121,
       7.74205814, 5.0270518 , 9.28249104, 8.85141163, 5.50693303,
       8.21838517, 6.70653306, 7.67322795, 6.06367024, 6.81908787])

In [17]:
#Operações com arrays (podem ser usados + - * / e **)
arr1 = np.arange(0, 21)


In [18]:
#No exemplo, uso a soma entre dois arrays
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [19]:
#Retorna a raíz quadrada de um array
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [20]:
#Calcula a média dos elementos
np.mean(arr1)

10.0

In [21]:
#Desvio padrão
np.std(arr1)

6.0553007081949835

In [22]:
#Mediana
np.median(arr1)

10.0

In [23]:
#Salvando um array como .txt
np.savetxt('arrand.txt',arrand, delimiter=',')

# Carregar arrays a partir de um arquivo

In [24]:
dataset = np.loadtxt('arrand.txt', delimiter=',')
dataset

array([[4.42924855, 8.1720853 , 4.50461774, 5.76370637, 6.5574627 ,
        8.29466856, 3.96187779, 1.09078561, 3.63081713, 3.51868521],
       [1.56413047, 5.82704941, 3.70321458, 8.0662472 , 3.74347052,
        6.18467371, 9.0243331 , 2.50463844, 3.26299624, 1.20181728],
       [6.22116244, 3.03907868, 2.30957063, 5.38921121, 3.11255263,
        7.74205814, 1.03219076, 5.0270518 , 9.28249104, 8.85141163],
       [2.33242919, 4.09859797, 5.50693303, 3.49919772, 2.42128181,
        8.21838517, 0.86824657, 6.70653306, 3.45181217, 1.09764942],
       [4.76432631, 0.96678733, 7.67322795, 3.25164385, 0.6066504 ,
        6.06367024, 6.81908787, 1.15318083, 2.89319376, 0.56953321]])

In [25]:
dataset.shape

(5, 10)

In [26]:
a,b,c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True)

In [27]:
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [28]:
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [29]:
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [30]:
a,b,c

(array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993]),
 array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357]),
 array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ]))

In [35]:
#Carrega um dataset ignorando as 2 primeiras linhas e trocando NaNs e strings por 0
ds = np.genfromtxt("dataset_valores_vazio.txt", skip_header=2, filling_values=0)
ds

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])